### ISSUE TITLE
Use Data URLs, not Object URLs

### ISSUE THREAD

**Issue by coolaj86** [MaxSultan/img-compressor#11]
https://github.com/MaxSultan/img-compressor/blob/ec1d73aa3991aa25f9feedd82123a40032a1d64b/js/index.js#L79

An object URL is essentially a pointer to a location that exists in RAM. You cannot copy and paste it (or you can, but it won’t copy and paste anything useful).

A Data URL can be copied and pasted or otherwise embedded in HTML as a real value. If you were to save the file, the image would literally be in the file.

You can include Data URLs in an e-mail, but an Object URL would have no meaning to the browser receiving it.

**Comment by MaxSultan** [comment]
This is added as a part of pull request https://github.com/MaxSultan/img-compressor/pull/14
