### ISSUE TITLE
Use permanent event handlers

### ISSUE THREAD

**Issue by coolaj86** [MaxSultan/img-compressor#13]
https://github.com/MaxSultan/img-compressor/blob/41210208fe93ebc1042f5642154ecbe3c2062521/js/index.js#L130

it’s better to either use DOM events, or to attach the event handlers in the html.

```js
function listen(sel, event) {
    // only ever addEventListener to 'body' or 'form' and then check ev.target
    document.querySelector('body').addEvenListner(event, function (ev) {
        if (!ev.target.matchesSelector(sel)) {
            return true;
        }
        // …
    });
}
```

or

```html
<button onclick="Foo.save(event);">Save</button>
```

If you do either of those then your event handlers will work as you add and remove items from the page, and on lists of items.

If you use shallow handlers with `el.onclick=` in JavaScript (or adding a listener _directly_ onto an element) you’ll run into problems as you scale out where some elements respond and others don’t, or fire twice, etc (because the logic of adding the handlers becomes inconsistent with the logic that renders the elements).

**Comment by MaxSultan** [comment]
This is added in pull request https://github.com/MaxSultan/img-compressor/pull/16
