### ISSUE TITLE
0-effort demo (takes 30 seconds)

### ISSUE THREAD

**Issue by coolaj86** [MaxSultan/img-compressor#2]
This will take you 30 seconds:

0. Click Settings
1. Click Pages
2. Select Source Branch
3. Enforce HTTPS

![Screen Shot 2021-07-20 at 11 40 11 AM](https://user-images.githubusercontent.com/122831/126372201-2369e1da-b4f3-4034-8757-85b445b8f8a1.png)

**Comment by coolaj86** [comment]
Also need the link:

![Screen Shot 2021-07-20 at 12 01 26 PM](https://user-images.githubusercontent.com/122831/126373168-b2cb15a5-88e9-4df7-b78a-f276538357c9.png)

**Comment by MaxSultan** [comment]
Demo is added!
