### ISSUE TITLE
Bug: Clicking "Copy Data URL" has no visual feedback

### ISSUE THREAD

**Issue by coolaj86** [MaxSultan/img-compressor#22]
Clicking on a button should cause visual feedback (typically that the button become darker, or appear to depress).

This may be a bug in MVP.css, but even if so you could fix it by adding a CSS style, and/or by adding some text (ex: "Copied").

```html
<style>
button:active {
    filter: brightness(85%);
}
</style>
```

**Comment by coolaj86** [comment]
I've created a PR for MVP.css:
https://github.com/andybrewer/mvp/pull/68

**Comment by MaxSultan** [comment]
Added visual feedback iAugust 10th in https://github.com/MaxSultan/img-compressor/pull/23
