### ISSUE TITLE
Support Copy/Paste + Drag'n'Drop

### ISSUE THREAD

**Issue by coolaj86** [MaxSultan/img-compressor#4]
If I alt-click **Copy Image** on a web page and I <kbd>Cmd ⌘</kbd> + <kbd>v</kbd> in Twitter, for example, it handles it has a file upload.

Likewise if I drag and drop and image it also handles it as an upload.

Can you demonstrate these as well?

**Comment by coolaj86** [comment]
It looks like this is as simple as listening for the `paste` event on a container element (perhaps `body`) and then forwarding it on to the file handler: https://stackoverflow.com/a/59769604/151312

**Comment by MaxSultan** [comment]
Copy paste is completed as apart of this PR https://github.com/MaxSultan/img-compressor/pull/21

**Comment by coolaj86** [comment]
Awesome! Love it!

It needs some sort of indicator to let the person know that they can paste the image. I think that could be accomplished in tandem with the URL input:

```html
<label>Paste an Image or Image URL:
    <input type="url" ... />
</label>
```

I'm assuming that the input will neither inhibit nor respond to the event, but it will provide an area for the user to click and feel as though the paste is meaningful and effective in at least that area.

**Comment by MaxSultan** [comment]
Drag and drop added Aug10th in PR https://github.com/MaxSultan/img-compressor/pull/23

**Comment by MaxSultan** [comment]
Paste indicator added August 10th in https://github.com/MaxSultan/img-compressor/pull/24
