### ISSUE TITLE
Max Width / Max Height should be two fields

### ISSUE THREAD

**Issue by coolaj86** [MaxSultan/img-compressor#8]
We want to be able to constrain the maximum width and height, as either may be the bigger number - and some images may be in portrait while others are in landscape, but all need to fit into the same allotted space.

```txt
Maximum Dimensions (in pixels):
H: ________ x W: ________
```

Only constrain height:

```txt
Maximum Dimensions (in pixels):
H: __300__ x W: ________
```

Only constrain width:

```txt
Maximum Dimensions (in pixels):
H: ________ x W: __300__
```

Constrain both:

```txt
Maximum Dimensions (in pixels):
H: __300__ x W: __300__
```

**Comment by MaxSultan** [comment]
I chose to do it this way because it allows us the freedom to preserve the aspect ratio of the image. How would I communicate that best to the user while still allowing the options of setting both dimensions?

**Comment by coolaj86** [comment]
"Maximum Dimensions (in pixels, aspect ratio preserved)"

**Comment by coolaj86** [comment]
I think the idea of smooshing and distorting the image is so absurd that "Maximum Dimensions" alone is clear enough - who would want that behavior?

Or maybe a checkbox
- [ ] Make image ugly and distorted?

**Comment by coolaj86** [comment]
```
<style>
    fieldset {
        border-style: none;
    }
    fieldset label {
        display: inline-block;
    }
</style>
<fieldset>
    <label>H: <input type="number" step="1" min="0"></label>
    x
    <label>H: <input type="number" step="1" min="0"></label>
    <label><input type="checkbox" checked onclick="window.alert('You\'re a monster!'); return false; this.checked = true; this.value = true;"> Preserve Aspect Ratio</label>
</fieldset>
```

**Comment by MaxSultan** [comment]
Should the text in this label say "Ignore aspect ratio"?

**Comment by MaxSultan** [comment]
Nevermind, I misunderstood

**Comment by MaxSultan** [comment]
Implemented as a part of https://github.com/MaxSultan/img-compressor/pull/9
